Base class RawOffer in scraper.py
eikowagenknecht/lootscraper pull request #76
Opened 2022-06-23 21:11 UTC by TrueMilli

I thought this would help for categorizing offers but it doesn't.
I think it will still be helpful to harmonize things.

There are still specific RawOffers for several services but those could be harmonized in the future as well.

2022-06-24 13:52 UTC, eikowagenknecht requested changes
See inline comments

2022-06-24 13:52 UTC, eikowagenknecht commented on app/scraper/loot/steam_loot.py
> +from app.scraper.loot.steam_games import SteamRawOffer
The scrapers are meant to be independent of each other, please don't cross reference them

2022-06-24 13:55 UTC, TrueMilli commented on app/scraper/loot/scraper.py
> +        return raw_offers  # ToDo: Implement this method
```suggestion
```

2022-06-24 13:56 UTC, TrueMilli commented on app/scraper/loot/scraper.py
> +        return raw_offers  # ToDo: Implement this method
```suggestion
```

2022-07-02 19:24 UTC, eikowagenknecht approved these changes
lgtm

2022-07-02 19:28 UTC, merged